[project]
name = "api-spotify"
version = "0.0.1b07"
description = "Wrapper for spotify APIs"
readme = "README.md"
requires-python = ">=3.12"
authors = [
	{ name = "An0nimia", email = "an0nimia@protonmail.com" },
]
dependencies = [
	"pydantic (>=2.11.7,<3.0.0)",
	"requests (>=2.32.4,<3.0.0)",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
